name: crystal_navigation_bar
description: Sleek, crystal-clear blur bottom navigation bar with dynamic indicator for seamless app navigation.
version: 2.0.0
homepage: https://github.com/immi420/crystal_navigation_bar
repository: https://github.com/immi420/crystal_navigation_bar
issue_tracker: https://github.com/immi420/crystal_navigation_bar/issues
topics:
  - ui
  - navigation
  - bottom-navigation
  - blur
funding:
  - https://buymeacoffee.com/immi420

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
