name: crystal_navigation_bar
description: Sleek, crystal-clear blur bottom navigation bar with dynamic indicator for seamless app navigation.
version: 1.0.4
#authors: Imtiaz Ahmad -twitter [its_immi]
homepage: https://github.com/immi420/crystal_navigation_bar
repository: https://github.com/immi420/crystal_navigation_bar
issue_tracker: https://github.com/immi420/crystal_navigation_bar/issues
topics:
  - crystal-navigation-bar
  - bottomnavigation
  - blurnavbar
funding:
  - https://buymeacoffee.com/immi420

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:



